"""Shared application constants."""

PROCESSING_STATUS_COMPLETED = "completed"
PROCESSING_STATUS_RULE_ONLY = "rule_only"
PROCESSING_STATUS_LLM_OUTPUT_INVALID = "llm_output_invalid"
PROCESSING_STATUS_TIMEOUT = "timeout"
PROCESSING_STATUS_ERROR = "error"

REASONING_QUALITY_STRONG = "strong"
REASONING_QUALITY_PARTIAL = "partial"
REASONING_QUALITY_WEAK = "weak"
REASONING_QUALITY_UNKNOWN = "unknown"

