"""
training/train_lightgbm.py

Trains the first baseline LightGBM LambdaRank model on the production
synthetic bootstrap dataset (training/artifacts/train.parquet +
validation.parquet, generated by generate_production_dataset.py from the
approved SyntheticUserGenerator -> DatasetGenerator -> LabelGenerator
pipeline).

Feature selection is NOT hardcoded here: the trainable column list and the
categorical column list both come directly from
training/feature_registry.py::FeatureRegistry.model_matrix_features()/
categorical_features() -- the single source of truth the rest of the
training pipeline already uses. Adding/removing a feature only requires
changing the registry; this script picks it up automatically.

Run:
    python -m training.train_lightgbm
"""
from __future__ import annotations

import itertools
import json
import time
from typing import Optional

import lightgbm as lgb
import numpy as np
import pandas as pd

from training.config import (
    FEATURE_IMPORTANCE_CSV_PATH,
    FEATURE_IMPORTANCE_JSON_PATH,
    LIGHTGBM_MODEL_PATH,
    MODEL_METADATA_PATH,
    RANDOM_SEED,
    TRAIN_DATASET_PATH,
    TRAINING_CONFIG_PATH,
    TRAINING_METRICS_PATH,
    VALIDATION_DATASET_PATH,
)
from training.feature_registry import build_default_registry
from training.model_metadata import build_metadata, save_metadata

NUM_BOOST_ROUND = 1000
EARLY_STOPPING_ROUNDS = 50
EVAL_AT = [1, 3, 5, 10]   # ranks NDCG is evaluated at -- covers this dataset's query-group size range (2-10)

LGB_PARAMS = {
    "objective": "lambdarank",
    "metric": "ndcg",
    "eval_at": EVAL_AT,
    "boosting_type": "gbdt",
    "learning_rate": 0.05,
    "num_leaves": 31,
    "min_data_in_leaf": 20,
    "lambdarank_truncation_level": 10,   # >= max query-group size in this dataset (10)
    "seed": RANDOM_SEED,
    "deterministic": True,
    "force_row_wise": True,   # required alongside deterministic=True for bit-identical repeat runs
    "num_threads": 1,          # single-threaded: the only way LightGBM guarantees determinism
    "verbose": -1,
}


def _query_groups(df: pd.DataFrame) -> np.ndarray:
    """
    LightGBM's `group` array is the size of each CONSECUTIVE block of rows
    belonging to one query_id, in row order -- not a value_counts() (which
    would reorder groups alphabetically by query_id and silently desync
    every row from its group boundary). DatasetGenerator.generate_dataframe
    sorts by (user_id, recommended_at, query_id) before any row is emitted,
    and split_train_validation's boolean-mask filtering preserves that row
    order, so every query_id's rows are already contiguous here -- this
    only extracts the block sizes, it does not re-sort anything.
    """
    query_ids = df["query_id"].to_numpy()
    return np.array([len(list(g)) for _, g in itertools.groupby(query_ids)])


def _prepare_features(df: pd.DataFrame, feature_names: list[str],
                       categorical_names: list[str],
                       categories: Optional[dict[str, pd.CategoricalDtype]] = None,
                       ) -> tuple[pd.DataFrame, dict[str, pd.CategoricalDtype]]:
    """
    Casts every trainable column to a LightGBM-friendly dtype:
      - categorical columns (currently just user_level) -> pandas 'category',
        with the SAME category set fit on train and reused for validation
        (via `categories`) so category codes line up across both splits.
      - everything else -> float64 (bool True/False -> 1.0/0.0; an
        all-missing column like company_tag_count stays all-NaN, which
        LightGBM treats natively as a missing value, not an error).
    Does not fabricate any value -- NaN stays NaN.
    """
    X = df[feature_names].copy()
    fitted_categories: dict[str, pd.CategoricalDtype] = {}

    for col in feature_names:
        if col in categorical_names:
            if categories is not None and col in categories:
                X[col] = X[col].astype(categories[col])
            else:
                X[col] = X[col].astype("category")
                fitted_categories[col] = X[col].dtype
        else:
            X[col] = X[col].astype("float64")

    return X, fitted_categories


def main():
    t_start = time.time()

    registry = build_default_registry()
    trainable_specs = registry.model_matrix_features()
    feature_names = [f.name for f in trainable_specs]
    categorical_names = [f.name for f in registry.categorical_features()]

    train_df = pd.read_parquet(TRAIN_DATASET_PATH)
    validation_df = pd.read_parquet(VALIDATION_DATASET_PATH)

    missing_in_train = set(feature_names) - set(train_df.columns)
    if missing_in_train:
        raise ValueError(f"Registry declares features missing from train.parquet: {sorted(missing_in_train)}")

    print(f"Train: {train_df.shape[0]} rows, {train_df['query_id'].nunique()} query groups")
    print(f"Validation: {validation_df.shape[0]} rows, {validation_df['query_id'].nunique()} query groups")
    print(f"Trainable features ({len(feature_names)}): {feature_names}")
    print(f"Categorical features: {categorical_names}")

    train_groups = _query_groups(train_df)
    validation_groups = _query_groups(validation_df)
    assert train_groups.sum() == len(train_df)
    assert validation_groups.sum() == len(validation_df)

    X_train, fitted_categories = _prepare_features(train_df, feature_names, categorical_names)
    X_validation, _ = _prepare_features(
        validation_df, feature_names, categorical_names, categories=fitted_categories,
    )

    y_train = train_df["label"].astype("float64")
    y_validation = validation_df["label"].astype("float64")
    if y_train.isna().any() or y_validation.isna().any():
        raise ValueError("Found NaN labels in train/validation -- these rows should never have "
                          "been exported (LabelGenerator.validate() should have caught this).")

    train_set = lgb.Dataset(
        X_train, label=y_train, group=train_groups,
        categorical_feature=categorical_names or "auto", free_raw_data=False,
    )
    validation_set = lgb.Dataset(
        X_validation, label=y_validation, group=validation_groups,
        categorical_feature=categorical_names or "auto", reference=train_set, free_raw_data=False,
    )

    evals_result: dict = {}
    t_train_start = time.time()
    booster = lgb.train(
        params=LGB_PARAMS,
        train_set=train_set,
        num_boost_round=NUM_BOOST_ROUND,
        valid_sets=[train_set, validation_set],
        valid_names=["train", "validation"],
        callbacks=[
            lgb.early_stopping(stopping_rounds=EARLY_STOPPING_ROUNDS, verbose=True),
            lgb.log_evaluation(period=25),
            lgb.record_evaluation(evals_result),
        ],
    )
    training_seconds = round(time.time() - t_train_start, 2)

    # ------------------------------------------------------------- save model
    LIGHTGBM_MODEL_PATH.parent.mkdir(parents=True, exist_ok=True)
    booster.save_model(str(LIGHTGBM_MODEL_PATH), num_iteration=booster.best_iteration)

    # ------------------------------------------------------------- feature importance
    gain_importance = booster.feature_importance(importance_type="gain")
    split_importance = booster.feature_importance(importance_type="split")
    importance_df = pd.DataFrame({
        "feature": booster.feature_name(),
        "gain": gain_importance,
        "split": split_importance,
    }).sort_values("gain", ascending=False).reset_index(drop=True)
    importance_df["gain_pct"] = round(100.0 * importance_df["gain"] / importance_df["gain"].sum(), 4)

    importance_df.to_csv(FEATURE_IMPORTANCE_CSV_PATH, index=False)
    with open(FEATURE_IMPORTANCE_JSON_PATH, "w", encoding="utf-8") as fh:
        json.dump(importance_df.to_dict(orient="records"), fh, indent=2, default=str)

    # ------------------------------------------------------------- training metrics
    best_iteration = booster.best_iteration
    best_scores = {
        dataset_name: {metric: values[best_iteration - 1] for metric, values in metrics.items()}
        for dataset_name, metrics in evals_result.items()
    }

    training_metrics = {
        "training_seconds": training_seconds,
        "total_seconds": round(time.time() - t_start, 2),
        "num_boost_round_requested": NUM_BOOST_ROUND,
        "num_boost_round_completed": booster.current_iteration(),
        "early_stopping_rounds": EARLY_STOPPING_ROUNDS,
        "best_iteration": best_iteration,
        "best_scores": best_scores,
        "eval_history": evals_result,
        "train_rows": int(train_df.shape[0]),
        "validation_rows": int(validation_df.shape[0]),
        "train_query_groups": int(len(train_groups)),
        "validation_query_groups": int(len(validation_groups)),
    }
    with open(TRAINING_METRICS_PATH, "w", encoding="utf-8") as fh:
        json.dump(training_metrics, fh, indent=2, default=str)

    # ------------------------------------------------------------- training config
    training_config = {
        "random_seed": RANDOM_SEED,
        "lgb_params": LGB_PARAMS,
        "num_boost_round": NUM_BOOST_ROUND,
        "early_stopping_rounds": EARLY_STOPPING_ROUNDS,
        "eval_at": EVAL_AT,
        "feature_names": feature_names,
        "categorical_features": categorical_names,
        "n_features": len(feature_names),
        "train_dataset_path": str(TRAIN_DATASET_PATH),
        "validation_dataset_path": str(VALIDATION_DATASET_PATH),
        "train_rows": int(train_df.shape[0]),
        "validation_rows": int(validation_df.shape[0]),
        "train_query_groups": int(len(train_groups)),
        "validation_query_groups": int(len(validation_groups)),
        "query_group_size_stats": {
            "train": {
                "min": int(train_groups.min()), "max": int(train_groups.max()),
                "mean": round(float(train_groups.mean()), 4),
            },
            "validation": {
                "min": int(validation_groups.min()), "max": int(validation_groups.max()),
                "mean": round(float(validation_groups.mean()), 4),
            },
        },
    }
    with open(TRAINING_CONFIG_PATH, "w", encoding="utf-8") as fh:
        json.dump(training_config, fh, indent=2, default=str)

    # ------------------------------------------------------------- model metadata
    metadata = build_metadata(
        feature_names=feature_names,
        training_rows=int(train_df.shape[0]),
        validation_rows=int(validation_df.shape[0]),
        query_groups_train=int(len(train_groups)),
        query_groups_validation=int(len(validation_groups)),
        random_seed=RANDOM_SEED,
        best_iteration=best_iteration,
        training_parameters=training_config,
        training_metrics=best_scores,
        model_file_name=LIGHTGBM_MODEL_PATH.name,
    )
    save_metadata(metadata)

    # ------------------------------------------------------------- report
    print(f"\nBest iteration: {best_iteration} / {booster.current_iteration()} boosting rounds completed")
    print(f"Training time: {training_seconds}s")
    print("Best validation scores:", json.dumps(best_scores.get("validation", {}), indent=2))
    print("\nTop 20 features by gain:")
    print(importance_df.head(20).to_string(index=False))
    print(f"Model version: {metadata.model_version}")
    print(f"\nWrote:\n  {LIGHTGBM_MODEL_PATH}\n  {FEATURE_IMPORTANCE_CSV_PATH}\n"
          f"  {FEATURE_IMPORTANCE_JSON_PATH}\n  {TRAINING_METRICS_PATH}\n  {TRAINING_CONFIG_PATH}\n"
          f"  {MODEL_METADATA_PATH}")


if __name__ == "__main__":
    main()
